volumes:
  kc_data:
    name: keycloak-devenv
services:
  keycloak:
    container_name: keycloak-devenv
    image: quay.io/keycloak/keycloak:26.0.7
    command: start-dev
    environment:
      DEBUG: 'true'
      DEBUG_PORT: '*:8787'
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - '8080:8080'
      - '8787:8787'
    volumes:
      - kc_dataa:/opt/keycloak/data
      - ./target/ip-conditional-authenticator-1.0-SNAPSHOT.jar:/opt/keycloak/providers/ip-conditional-authenticator-1.0-SNAPSHOT.jar
    extra_hosts:
      - "host.docker.internal:host-gateway"
